name: build
on: [push, pull_request]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@v2
      - name: Install COBOL
        run: sudo apt-get install -y open-cobol
      - name: Compile
        run: cobc -x cobol.cbl
